#!/bin/bash
Year=`date +%Y`
Month=`date +%m`
Day=`date +%d`
Hour=`date +%H`
Minute=`date +%M`
Second=`date +%S`

tput setab 4;
tput setaf 3;
echo
echo
echo "	Time and date:"

echo
echo "	$Hour:$Minute:$Second"

echo "	$Day.$Month.$Year"
echo